### ISSUE TITLE
Visão e Missão do ProdOps

### ISSUE THREAD

**Issue by cmilfont** [prodops-university/prodops-spec#4]
## Visão

|                |                 |                 
|---------|----------|
| Para                 |   Instituições e profissionais  |
| Que precisam |  construir ou resgatar uma cultura de produtos digitais e compreendem que este conjunto de disciplinas é a abordagem mais eficaz para atuar tanto no digital quanto em soluções que são apoiadas por tecnologia |
| Framework ProdOps é uma     |  especificação de como implantar valores, princípios e, principalmente, técnicas seguindo estratégias definidas   |
| Que                  | alinham TI e negócio, aceleram as entregas e criam uma transição do modelo tradicional ou de uma situação frágil com o Roadmap bastante fragmentado para a cultura Product-led |
| Diferente de   | outras abordagens de Product Operations que apenas contextualizam respostas do "Porquê" e "Para quê"(*5W2H) |
| ProdOps         |  garante um formato de execução que administra, fiscaliza, avalia e executa essa jornada de transição ou restauração do Product-led |

### * [5W2H](https://en.wikipedia.org/wiki/Five_Ws)
Os 5W:  
What (o que será feito?)  
Why (por que será feito?)  
Where (onde será feito?)  
When (quando será feito?)  
Who (por quem será feito?)  

Os 2H:  
How (como será feito?)  
How much(quanto vai custar?)  

## Missão

A missão do Framework é aumentar o rigor da engenharia de produto de forma iterativa e incremental a partir da visão do ProdOps, utilizando técnicas que garantem a comunicação eficaz entre todos os participantes do início ao fim do serviço ao cliente, respeitando a estrutura, cultura, papéis e cargos existentes.

O ProdOps funciona de forma complementar a qualquer método ou abordagem adotada, sugerindo melhorias contínuas sem impor mudanças drásticas, garantindo assim uma integração suave e eficiente.

  | Product-Led | ProdOps | Tradicional
-- | -- | -- | --
Propósito | Guiar a companhia em volta de produtos que entregam experiência do negócio ao clientes | Entender a cultura da empresa harmonizando a transição do modelo tradicional para Product-Led em torno de 4 verticais de interesse: Construção dos times adequados, momento do negócio, satisfação do cliente e tecnologia suficiente. | Guiar os resultados da companhia empregando tecnologia com novas funcionalidades no menor custo e capacidade possível para apoiar o negócio
Estratégia | Pessoas apoiando Software | Eliminação do trabalho repetitivo e manual para construção da cultura de produto | Software apoiando Pessoas
Colaboração | Squads multidisciplinares com pessoas de todos os perfis: Comercial, Mkt, Tech, Operação construindo produtos | Identificação de dependências para construção de times multidisciplinares em torno do momento do produto independente da estrutura da organização | Áreas trabalhando em suas atividades primárias e fornecendo pessoas para projetos em conjunto por tempo determinado para construção das plataformas de apoio ao negócio
Clientes | Foca para entregar necessidades ou oportunidades de valor para conquistar e manter o cliente | Identificar os pontos de contato na jornada do cliente e como eles são entregues pela arquitetura existente mapeada na profundidade das Value Streams para construir ou readequar a fronteira correta dos produtos, | Foca em atividades do negócio para maximizar o lucro e entregar projetos definidos na estratégia do negócio
Métricas | Data-driven | Observabilidade em primeiro lugar para definir quais deficiências existem nas jornadas e  encontrar as métricas ideais pelo momento dos produtos ou Value Streams. | Metas de projetos estabelecidos para o ano ou Quarter e metas das áreas de negócios desassociadas das entregas
Descoberta | Validação frequente de hipóteses | Construção de um Roadmap compartilhado a partir da unificação dos fluxos entre as áreas de tecnologia, negócio e operação da empresa. | Sessões de Workshops na fase inicial de projetos ou na construção de RFPs com base no mercado e especialistas de negócio.
Planejamento | Estimativas sobre User Stories refinadas | Garantir que o rigor em cada jornada seja analisado e a melhoria suficiente na maturidade de cada capabilidade apresentada em plano de Confiabilidade para eliminação dos TOILs identificados. | Estimativas sobre o mapeamento de todas as tarefas no detalhe
Entrega | Continuous Delivery | Evolução do modelo de entrega na direção do estado da arte da automatização quiado pela maturidade necessária para atingir o Time To Market | GMUD com entendimento antigo sobre ITIL
Operação | Equipes do produto operam os serviços em produção | Construção de um ambiente informativo para garantir que as áreas de negócio tenham uma colaboração em tempo real com os times de tecnologia e cada equipe atue em sua camada de intervenção garantindo que o incidente é capturado antes do usuário notificar | Separação entre Projeto e Sustentação

**Comment by thalesfaggiano** [comment]
# Outras definições

Melissa Perri e Denise Tilles definem no livro Product Operations:
" Product Operations is the discipline of helping your Product Management function scale well. Surrounding the team with all of the essential inputs to set strategy, prioritize, and streamline ways of working."

**Comment by cmilfont** [comment]
https://produtoreativo.com.br/visao-e-missao-do-prodops/
